baseURL = "https://francoposa.io"
languageCode = "en-us"
theme = "basic"
title = "francoposa.io"

enableGitInfo = true

[markup]
[markup.highlight]
style = "friendly"

[params]
AuthorName = "Franco Posa"
Description = "Software Engineering and Technical Guides, Docs, and Blogs"
